---
abstract: "Collection of utilities for writing perl code that fits the DCI\nmethodology."
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Fennec: 1.011
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DCI
provides:
  DCI:
    file: lib/DCI.pm
    version: 0.002
  DCI::Cast:
    file: lib/DCI/Cast.pm
    version: 0
  DCI::Cast::Base:
    file: lib/DCI/Cast/Base.pm
    version: 0
  DCI::Context:
    file: lib/DCI/Context.pm
    version: 0
  DCI::Context::Base:
    file: lib/DCI/Context/Base.pm
    version: 0
requires:
  Carp: 0
  Exporter::Declare: 0
  Scalar::Util: 0
resources:
  bugtracker: http://github.com/exodist/DCI-Cast/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/DCI-Cast
version: 0.002
